services:

  db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: onecloud
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "mongodb://user:password@mongo_db:27017/onecloud?authSource=admin"
      EXTERNAL_API: "https://api-onecloud.multicloud.tivit.com/fake"

volumes:
  mongo_data:
